baseURL = "/"
languageCode = "en-us"
title = "Hello World, This Is J"
theme="galaxy"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/vjeantet"
weight = 100
[[menu.main]]
name = "Twitter timeline"
url = "https://twitter.com/vjeantet"
weight = 101
[[menu.main]]
name = "Flipboard magazines"
url = "https://flipboard.com/@vjeantet"
weight = 102
[[menu.main]]
name = "Keybase (secure msg)"
pre = "<h3>Contact me</h3>"
url = "https://Keybase.io/vjeantet"
weight = 109

[author]
  name = "J"

[params]
  description = "Find me above the cloud, nearby data lake"
  author = "J"
  authorlocation = ""
  authorwebsite = "https://sekiro-j.github.io/"
  bio= "Software/Big Data engineer, EV enthusiast, IoT/AI/Blockchain believer, a student"
  logo = "images/avatar.jpg"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "SEKIRO-J"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
