baseURL = "/"
languageCode = "en-us"
title = "Hello World, This Is J"
theme="galaxy"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/SEKIRO-J"
weight = 100
[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 101
[[menu.main]]
name = "LinkedIn"
pre = "<h3>Contact me</h3>"
url = "https://www.linkedin.com/in/junjie-gu-37790011a/"
weight = 109

[author]
  name = "J"

[params]
  description = "Find me above cloud, nearby data lake"
  author = "J"
  authorlocation = ""
  authorwebsite = "https://sekiro-j.github.io/"
  bio= "Software/Big Data engineer, EV enthusiast, IoT/AI/Blockchain believer, a student"
  logo = "images/avatar.jpg"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "SEKIRO-J"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
